### ISSUE TITLE
Wire library doesn't support Wire.endTransmission(false); problem in using adafruit mpr121 library.

### ISSUE THREAD

**Issue by engrziarehman** [rogerclarkmelbourne/Arduino_STM32#295] opened 2017-05-26 00:31 UTC
I have successfully used MPR121 touch sensor with arduino mega board. but facing problem in compiling with stm32f103c8 board, since the wire library doesn't support repeated start feature. following is the code that is unable to compile
```

uint8_t Adafruit_MPR121::readRegister8(uint8_t reg) {
    Wire.beginTransmission(_i2caddr);
    Wire.write(reg);
    **Wire.endTransmission(false);**
    while (Wire.requestFrom(_i2caddr, 1) != 1);
    return ( Wire.read());
}

uint16_t Adafruit_MPR121::readRegister16(uint8_t reg) {
    Wire.beginTransmission(_i2caddr);
    Wire.write(reg);
    **Wire.endTransmission(false);**
    while (Wire.requestFrom(_i2caddr, 2) != 2);
    uint16_t v = Wire.read();
    v |=  ((uint16_t) Wire.read()) << 8;
    return v;
}
```

**Comment by rogerclarkmelbourne** [comment] 2017-05-26 00:42
Isnt this a duplicate of https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/289 ?

**Comment by rogerclarkmelbourne** [comment] 2017-05-26 06:42
Just a thought....
But if you have hardware which requires this, perhaps you can test the change I proposed in #289

**Comment by engrziarehman** [comment] 2017-07-14 18:25
the change you proposed in #289 is for adding a stop condition, but i have a problem to not to send stop condition during Wire.endtransmission(); because MPR121 is the device that works on repeated start method, means starting transmission again without sending stop. so Arduino Wire library has this feature Wire.endtranmission(false); can be used for this purpose, as it is used in adafruit library. but Arduino_STM32 Wire library doesn't take this boolean argument. what change will i be required?

**Comment by rogerclarkmelbourne** [comment] 2017-07-16 09:43
OK. 

I'll take a look.

**Comment by rogerclarkmelbourne** [comment] 2017-07-31 04:03
This was fixed a while ago. Please retest and reopen if the problem presists

**Closed by rogerclarkmelbourne** 2017-07-31 04:03 UTC
