### ISSUE TITLE
macOS: libusb is not included, that dfu-util depends on

### ISSUE THREAD

**Issue by toyoshim** [rogerclarkmelbourne/Arduino_STM32#256] opened 2017-03-16 14:25 UTC
https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation

The document says now that dfu-util is included, users do not need to install it manually.
Actually, a binary is included, but it seems users still need to install libusb on which the distributed binary depends. Otherwise, it just aborts due to missing dylib on starting upload.

**Comment by rogerclarkmelbourne** [comment] 2017-03-16 21:52
What would you recommend to fix this ?

**Comment by toyoshim** [comment] 2017-03-17 03:36
Is it easy to build another dfu-util with a static library version of libusb and to push it into the repo.?

**Comment by rogerclarkmelbourne** [comment] 2017-03-17 04:31
I don't know

You could give it a try and make a PR with the updated version

**Comment by satoshinm** [comment] 2017-12-04 00:43
I had the same problem, not sure of a proper fix but this seems to work as a temporary workaround:

```sh
brew install libusb
sudo mkdir -p /opt/local/lib
sudo ln -s /usr/local/Cellar/libusb/1.0.21/lib/libusb-1.0.0.dylib /opt/local/lib/libusb-1.0.0.dylib
```

**Comment by rogerclarkmelbourne** [comment] 2017-12-04 01:16
@satoshinm 

Just out of curiosity, which version of MacOS are you using ?

**Comment by satoshinm** [comment] 2017-12-04 02:03
Just updated to the latest, macOS High Sierra 10.13.2 public beta 6 (but not sure if using the beta is significant)

**Comment by JBerg60** [comment] 2018-02-10 19:42
Same error here. Solution was to install libusb `brew install libusb`

**Comment by Cipher2600** [comment] 2018-05-27 23:04
I am getting the following error upon attempting to compile:

fork/exec /bin/arm-none-eabi-g++: no such file or directory
Error compiling for board Generic STM32F103C series.

I have done everything as stated and also built the libusb. I am new to this so any help would be great! I am running Sierra on a MacBook Pro.

**Comment by ratkins** [comment] 2019-02-28 13:38
Same issue for me on Mojave (10.14.3 (18D109)). `brew install libusb` (no other `ln` commands necessary) fixes it.

**Comment by stevstrong** [comment] 2019-09-16 08:28
Is this solved? Possible duplicate of #328 
Anyway, I have no Mac, so any help on this is appreciated.

**Comment by rogerclarkmelbourne** [comment] 2020-05-18 03:32
This issue has no activity for a long time , so I will close it

**Closed by rogerclarkmelbourne** 2020-05-18 03:32 UTC
Labels: help wanted
