### ISSUE TITLE
Weird passing of command line arguments in "Arduino_STM32/tools/win/maple_upload.bat"

### ISSUE THREAD

**Issue by ultrakiller2** [rogerclarkmelbourne/Arduino_STM32#573] opened 2018-11-04 21:55 UTC
Using "%1 %2 %3 %4 %5 %6 %7 %8 %9" seems strange, shouldn't "%*" be used?

**Comment by rogerclarkmelbourne** [comment] 2019-02-28 00:32
I doubt all the args are even used.

I've already cleaned the STLink upload script because most of the args are unused, I suspect the same applies to this.

**Comment by stevstrong** [comment] 2019-09-16 08:03
Can someone test whether the change suggested by @ultrakiller2 works correctly and does not cause side effects?

**Comment by rogerclarkmelbourne** [comment] 2019-09-16 08:15
I'm not sure what benefit this has.

Playtform.txt doesn't send 9 args to maple_upload.bat, it only sends 5 args.

`tools.maple_upload.upload.pattern="{path}/{cmd}" {serial.port.file} {upload.altID} {upload.usbID} "{build.path}/{build.project_name}.bin"`

AFIK we don't have the source code to the JAR file that handles the upload, and I don't know what would happen if it expects 9 args and the %* only sends 5 because thats what platform.txt sends

If this is really a problem, the best solution is to decompile the maple upload JAR and remove the need for any redundant args.

But since it works OK, it seems a lot of work for zero gain, apart from neatness

**Comment by stevstrong** [comment] 2019-09-16 08:18
Roger, I agree. Should we close then this issue?

**Comment by rogerclarkmelbourne** [comment] 2019-09-16 10:45
Yes. Close it.

Its not a bug.

**Comment by stevstrong** [comment] 2019-09-16 11:19
It's not a bug so I close it.

**Closed by stevstrong** 2019-09-16 11:19 UTC
