### ISSUE TITLE
including "SPI.h" in minimal sketches causes crash

### ISSUE THREAD

**Issue by madias123** [rogerclarkmelbourne/Arduino_STM32#112] opened 2015-09-09 11:20 UTC
Just as reminder, see
http://www.stm32duino.com/viewtopic.php?f=3&p=5806#p5806

**Comment by rogerclarkmelbourne** [comment] 2015-10-22 02:34
Thanks

**Comment by stevstrong** [comment] 2017-06-20 19:16
Trying to find the root cause, I posted to the forum, the issue needs more details how to reproduce the problem.

**Comment by rogerclarkmelbourne** [comment] 2017-06-20 23:28
Thanks.

As far as I'm aware, including SPI into bank.ino crashes

If the build is for the bootloader, it will have Serial USB, so its not really completely blank as Serial.begin gets called in the init

**Comment by stevstrong** [comment] 2019-09-16 08:22
I have to check this.

**Comment by stevstrong** [comment] 2019-09-20 19:35
Cannot reproduce this issue anymore, so I will close this.

**Closed by stevstrong** 2019-09-20 19:35 UTC
Labels: question
