### ISSUE TITLE
I2C/wire library: slave is not implemented

### ISSUE THREAD

**Issue by madias123** [rogerclarkmelbourne/Arduino_STM32#207] opened 2016-09-12 13:08 UTC
Just for the record, because from time to time there are the same questions and troubles in the forum:
No, we do not have a working slave configuration for I2c  (onReceive()....) yet.

Maybe an approach could be:
http://forums.leaflabs.com/forums.leaflabs.com/topic2429.html?id=1543

**Comment by rogerclarkmelbourne** [comment] 2016-10-01 06:11
The new STM Core appeare to have I2C slave. So I think perhaps anyone needing this, will probably end up having to use that core (Albeit only when its working on boards like the BluePill)

**Comment by DouglasPearless** [comment] 2017-02-25 10:32
Has anyone (now) implemented the slave I2C function for STM32?

**Comment by scargill** [comment] 2017-08-02 20:02
A lot of info out there - some say it is in, some say it is not - yet here, in the repository, nothing since February..  Does i2c slave work?

**Comment by rogerclarkmelbourne** [comment] 2017-08-02 22:43
AFIK. No one has sent me a PR etc to add I2C slave functionality.

**Comment by scargill** [comment] 2017-08-02 23:15
Hi Roger - For those of us new to this chip - there is a lot of nonsense out there - some say it IS there, some say it isn't... any chance you can take this as a request to add i2c slave functionality?   I have a NANO as an I2c slave which can serve as a really cheap peripheral for many different devices... and a year ago I spotted the STM32 board (blue pill?) which is very cheap... it seemed this would make a better alternative - at the time people had all sorts of reasons why I2c slave functionality would not work - I was asked to look at this again today and I seem no further forward.... is it practical to make it so that it works just in the same way the WIRE library works in Arduino ? and if so - are you able to do that?

**Comment by scargill** [comment] 2017-08-02 23:17
and if so - which board are you supposed to select to get the generic stm32f103 boards to work?

**Comment by rogerclarkmelbourne** [comment] 2017-08-02 23:39
The issue is not the board. The issue is the core.

Have you looked at STM's own official Arduino core, rather than this incomplete / unofficial one

See

https://github.com/stm32duino

**Comment by stevstrong** [comment] 2019-09-16 08:25
Possible duplicate of #613 and #625 .

**Closed** 2019-10-04 14:03 UTC
Labels: duplicate
