### ISSUE TITLE
I2Cscan don´t work. process have no timeout

### ISSUE THREAD

**Issue by arnold-b** [rogerclarkmelbourne/Arduino_STM32#678] opened 2019-09-18 05:37 UTC
Hello, 
if i try your scanner sample with F103VCT6 it just wait endless and sometimes it goes one step. 

Even i setup manualy int8 res = i2c_master_xfer(sel_hard, &itc_msg, 1, 1000); in process. It only works one more step. 

There must be somewhere a problem with I2C.

**Comment by rogerclarkmelbourne** [comment] 2019-09-18 05:55
AFIK. This can hang if the I2C pullups are incorrect.

**Comment by stevstrong** [comment] 2019-09-18 07:17
Possible duplicate of #637, #638 .

**Comment by arnold-b** [comment] 2019-09-18 07:23
Hello, You are right, I made wrong pullup. Now i always get error 3.

**Closed** 2019-09-22 06:55 UTC
Labels: bug, duplicate
