### ISSUE TITLE
Can't get Linux Mint 19.1 to recognize my board using the Stm32duino bootloader

### ISSUE THREAD

**Issue by mateusnazarioc** [rogerclarkmelbourne/Arduino_STM32#651] opened 2019-07-26 18:12 UTC
Hello everyone!
I've acquired a Maple Mini clone from Baite, the BTE14-07A. They said it came with the bootloader to use with Arduino, but I can't get it to work with both OS that I said above.
Especially in Mint(my main OS), I tried all stages of the tutorial and the COM doesn't list the Serial.
Installed the DFU-Util v0.8, but it didn't work too...
Should I try to install the bootloader again?
This is the error I'm getting when trying to upload to the board via Arduino IDE.
![Arduino_IDE_Upload](https://user-images.githubusercontent.com/44046504/61972342-b9a53a00-afb7-11e9-9b8b-d102c1fe0217.png)

Ah, and I'm also in the Perpetual Bootloader mode when trying to upload the sketch.

Thx for everything. Hope I can get this awesome board to work :)

**Comment by ssieb** [comment] 2019-07-26 20:49
Do you have a USB to 3.3V serial adapter?  I would recommend just using that to replace the bootloader with something you know is good.

**Comment by mateusnazarioc** [comment] 2019-07-27 00:17
> Do you have a USB to 3.3V serial adapter? I would recommend just using that to replace the bootloader with something you know is good.

Hey ssieb, thx for the reply! Gonna try this now....This is the "solution" that I thought too hahaha

**Comment by mateusnazarioc** [comment] 2019-07-27 00:29
So, I got this error...
![image](https://user-images.githubusercontent.com/44046504/61987356-626d8c80-afec-11e9-9d88-0b1d958b4feb.png)
Any ideas?

**Comment by mateusnazarioc** [comment] 2019-07-27 00:29
I've got it both on the Arduino IDE trying to upload via Serial and via stm32flash to upload the binary

**Comment by mateusnazarioc** [comment] 2019-07-27 00:43
So, after some tries, I was able to install the bootloader on the board. It starts with the 6 fast blinks, then the slow blinks, and then stops.
But I'm getting the same error in the Arduino IDE...
Any ideas?

**Comment by Combinacijus** [comment] 2019-08-11 12:21
I have same problem on Ubuntu 18.04

```
Waiting for /dev/ttyACM0 serial...Done
dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: No DFU capable USB device available
```

Interesting thing is that I have uploaded bootloader and on two STM32 and they are fully working on Window 10 Arduino IDE. I can upload code and open serial monitor everything ok.
But on Ubuntu can't upload code. Manage to open serial monitor tho.
You can also open serial in terminal by: `cat /dev/ttyACM0` at first it didn't work but found that after `sudo apt-get purge modemmanager` it started working (don't know why or consequences).

It's been a real pain to get to this point on Ubuntu, any ideas?

**Comment by ssieb** [comment] 2019-08-11 20:14
Because it shows up as an ACM device, it looks like a modem, which means that ModemManager will check to see if it is.  On Fedora, I just disabled ModemManger using systemctl.  If you aren't expecting to use a modem, then removing it should be fine as well.

**Comment by stevstrong** [comment] 2019-09-15 07:48
What is the status of this issue? It it solved? Can be closed?

**Comment by stevstrong** [comment] 2019-09-16 12:41
Possible duplicate of #585

**Comment by rogerclarkmelbourne** [comment] 2020-02-09 10:15
I'm going to close this, as there has been no activity from the OP for around 6 months

**Closed by rogerclarkmelbourne** 2020-02-09 10:15 UTC
Labels: duplicate
