### ISSUE TITLE
Dynamixel Serial library on SERIAL 1

### ISSUE THREAD

**Issue by hassankord** [rogerclarkmelbourne/Arduino_STM32#510] opened 2018-04-27 17:00 UTC
dear,
i am using Dynamixel Serial library 
https://github.com/zcshiner/Dynamixel_Serial

void DynamixelClass::begin(long baud){

#if defined(__AVR_ATmega32U4__) || defined(__MK20DX128__) || defined(__AVR_ATmega2560__)
    Serial1.begin(baud);  // Set up Serial for Leonardo and Mega
    _serial = &Serial1;
#else
    Serial.begin(baud);   // Set up Serial for all others (Uno, etc)
    _serial = &Serial;

}
when I migrate my code from arduino mega to stm32f103c  i receive the following error 
error: 'UCSR0A' was not declared in this scope

     if ((UCSR0A & B01100000) != B01100000){                                             // Wait for TX data to be sent

Best Regards,
Hassan

**Comment by rogerclarkmelbourne** [comment] 2018-04-28 06:40
Thats because UCSR0A  is some sort of AVR specific register.

As per the Readme. All support if via the community forum www.stm32duino.com

I'm closing this now as its not a bug in the core, its a library for AVR hardware that won't work on STM32 without modification

**Closed by rogerclarkmelbourne** 2018-04-28 06:40 UTC
